# 1.gram-schmidt Algorithm

In [1]:
import numpy as np
from numpy import linalg as LA  #ユークリッドノルム
import random

In [2]:
def gram(a,b):
    return ((np.dot(a,b)/np.dot(a,a))*a)

　　ベクトル
  
$$[3,2,1]^{T},[2,1,3]^{T},[1,3,2]^{T}$$

　　に対して、

In [3]:
#直交ベクトル
a=np.array([3,2,1])
b=np.array([2,1,3])
c=np.array([1,3,2])

$$u_{1}=v_{1}\\u_{2}=v_{2}-proj_{u1}(v_{2})\\u_{2}=v_{3}-proj_{u1}(v_{3})-proj_{u2}(v_{3})\\.....\\u_{k}=v_{k}-\sum_{j=1}^{k-1}proj_{uj}(v_{k})$$

In [4]:
Va=a
Vb=b-gram(Va,b)
Vc=c-gram(Va,c)-gram(Vb,c)
print(Va,Vb,Vc)
print(np.dot(Va,Vb))
#直交ベクトル

[3 2 1] [-0.35714286 -0.57142857  2.21428571] [-1.2   1.68  0.24]
0.0


$$e_{1}=\frac{u_{1}}{||u_{1}||}\\e_{2}=\frac{u_{2}}{||u_{2}||}\\......\\e_{k}=\frac{u_{k}}{||u_{k}||}$$

In [5]:
#絶対値
Ea=Va/LA.norm(Va,2)
Eb=Vb/LA.norm(Vb,2)
Ec=Vc/LA.norm(Vc,2)
print(Ea,Eb,Ec)
#絶対値

[0.80178373 0.53452248 0.26726124] [-0.15430335 -0.24688536  0.95668077] [-0.57735027  0.80829038  0.11547005]


# 2.gram-schmidt Algorithm of random array

 ランダムに得られるベクトルに対してグラムシュミット化を行うアルゴリズム

In [27]:
import numpy as np
from numpy import linalg as LA


dimension=2   #次元を指定する

def randomnumber(dimension):
    return np.random.random((dimension,dimension))

def gram(a,b):
    return ((np.dot(a,b)/np.dot(a,a))*a)

v=randomnumber(dimension)

u=np.zeros((dimension,dimension),dtype='float64')
u[0]=v[0]

x=0
sum=np.array([0,0],dtype='float64')

for a in range(1,dimension):
    for b in range(0,a):
        sum+=gram(u[b],v[a])
    u[a]=v[a]-sum
    
print(v)
print(u)

[[0.75696033 0.47797919]
 [0.7569424  0.03510697]]
[[ 0.75696033  0.47797919]
 [ 0.19992696 -0.31661792]]
